services:
  web:
    build: .
    container_name: django_app_billing
    ports:
      - 8000:8000
    volumes:
      - ./BillManagementSystem:/app
    depends_on:
      db:
          condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: postgres_db_billing
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    env_file:
      - .env  
    restart: unless-stopped

volumes:
    postgres_db: