# Generated by Django 5.2.6 on 2025-10-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0008_rename_customer_customerbiller_customuser_is_biller_and_more'),
        ('bms', '0009_auto_20251027_2042'),
    ]

    operations = [
    ]
