# Generated by Django 5.2.6 on 2025-10-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0011_biller_updated_at_customerbiller_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbiller',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
